name: Feature
description: Suggest an idea for a new feature or enhancement
title: "[FEAT]: "
labels: ["type/feature", "type/enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out!
  - type: textarea
    id: describe-need
    attributes:
      label: Describe the need
      description: What do you want to happen? What problem are you trying to solve?
      placeholder: Describe the need for the feature.
    validations:
      required: true
  - type: input
    id: thebastion_version
    attributes:
      label: TheBastion version
      description: Does this feature suggestion apply to a specific TheBastion version?
      placeholder: v3.11.01
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. If it is a missing feature from TheBastion, please add a link to corresponding documentation.  
        Please check your logs before submission to ensure sensitive information is redacted.
      render: Markdown
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/arkhn/terraform-provider-thebastion/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true