name: GitHub Actions CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', '1.20' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: make tools
      - run: make depscheck
      - run: make lint
      - run: make build
      - run: make test
  doc:
    if: ${{ success() }}
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Generate documentation 
        run: make generate
      - name: Add new documentation
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'docs: Github Action to generate docs'