name: GitHub Actions CI

on:
  push:
    branches: [main, og/ci]
  pull_request: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: make tools
      - run: make depscheck
      - run: make lint
      - run: make build
      - run: make test